### ISSUE TITLE
[Feat] Add routing for the feedback form page and improve the UI of the form

### ISSUE THREAD

**Issue by infernodragon456** [JollyJolli/HacktoberWall#102]
Hello, I wanted to add a link to the homepage to the feedback form, and also improve the UI of the form page. Please assign me to work on this issue!

**Comment by JollyJolli** [comment]
Thanks! This is something i have been wanting! Thank you!

**Comment by infernodragon456** [comment]
I have made some form page designs, please review them @JollyJolli so that I can go ahead and implement them.
![image](https://github.com/user-attachments/assets/d0691fbe-e641-4398-af08-e0167f4766f5)
![image](https://github.com/user-attachments/assets/c64a1edd-9d98-4bcb-ad15-27d2fb52dbfa)

**Comment by JollyJolli** [comment]
I LOVE IT!!!

**Comment by JollyJolli** [comment]
It looks very good, thank you, i only got one question, is the data stored?

**Comment by infernodragon456** [comment]
No, but we can implement it in one of two ways:
1) Use a backend and a database to process and store data.
2) Or use a library like EmailJS to directly send email to a fixed mail id from form.js

**Comment by JollyJolli** [comment]
Use the one that you prefer
