### ISSUE TITLE
FIX THIS

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#127]
So their is punking on the top of the website 💀 

![image](https://github.com/user-attachments/assets/d1213b20-1c90-4eaf-a20e-9868132088e8)

**Comment by Phanty78** [comment]
Lol, who push this XD. I will try to solve this fast but i got few time

**Comment by JollyJolli** [comment]
Dont worry, solve it later

**Comment by Phanty78** [comment]
Job is done.
