### ISSUE TITLE
Improve website performance

### ISSUE THREAD

**Issue by Phanty78** [JollyJolli/HacktoberWall#129]
The website's performance is poor, which makes browsing less pleasant and results in poor search engine ranking.
It's a good idea to carry out an audit and take corrective action.

Tasks : 

- [x] Transform all images files in webp 
- [x] Lazy loading for elements below the waterline
- [ ] Correctly size images 
- [x] Minify all files

![image](https://github.com/user-attachments/assets/5d263719-ac81-4734-8c58-c08de08346a7)

**Comment by JollyJolli** [comment]
Would you like to help on this?

**Comment by Phanty78** [comment]
Yeah sure !

**Comment by JollyJolli** [comment]
Perfect! You are welcome!

Pd: I Send you a message vía Twitter

**Comment by Phanty78** [comment]
Thanks, I've just replied.

**Comment by JollyJolli** [comment]
Hey there! Just out of curiosity, you have all ready implemented 3 of of 4 things, how is the web performace with that changes?

**Comment by Phanty78** [comment]
![image](https://github.com/user-attachments/assets/1a94ef0c-9679-4702-bc0c-c7209f3f5575)

A bit better, but i I'm going to have to go further, and as accessibility is deteriorating, we should be more vigorous with contributions on this point.

**Comment by JollyJolli** [comment]
Yeah, maybe have some more rules in the contributions, it’s not a bad idea.

**Comment by JollyJolli** [comment]
Yeah, we should edit the CONTRIBUTING file and be more strict. I will make it later and you tell me what you think
