### ISSUE TITLE
FIX: Doble theme toggle

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#138]
So the web is displaying a doble icon for the theme toggling, please remove one and ensure that the theme toggle works good.

![image](https://github.com/user-attachments/assets/4266498d-b427-4732-80dd-841691b372a6)

**Comment by harith-hacky03** [comment]
I'm eager to work on it, Can you assign me please?

**Comment by JollyJolli** [comment]
Happy contributing!

**Comment by harith-hacky03** [comment]
It's done , check it once and let me know if any changes is needed.

**Comment by Phanty78** [comment]
Solved thanks for the resolution.
