### ISSUE TITLE
Add a Search Bar for Participants

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#14]

**Comment by P-yiush07** [comment]
Can you assign me for this ? I am looking to contribute in hactober fest. If you can assign me to do this and if my pr is getting accepted then it will be really helpful for me.

thanks

**Comment by JollyJolli** [comment]
Hey sorry for the late response i was sleeping, but yes, i can assign you no problem!

**Comment by P-yiush07** [comment]
> Hey sorry for the late response i was sleeping, but yes, i can assign you no problem!

okk no worries, so basicallythe thing is you want a search bar to search users right ?

**Comment by JollyJolli** [comment]
Yeah, and for each letter i want it to update, so if i type "s" imidiatle shows all the results with "s", you got it?

**Comment by P-yiush07** [comment]
> Yeah, and for each letter i want it to update, so if i type "s" immediately shows all the results with "s", you got it?

Okk, Implementing it !

**Comment by JollyJolli** [comment]
Thx!

**Comment by JollyJolli** [comment]
Dont forget to click on "Development" to vinculate your fork with the issue

**Comment by P-yiush07** [comment]
check the PR i implemented it
#16

**Comment by JollyJolli** [comment]
Thanks!
