### ISSUE TITLE
[Bug]: missing comma in contributors.json

### ISSUE THREAD

**Issue by rhnas110** [JollyJolli/HacktoberWall#143]
**Describe the bug**
There missing comman in contributors.json

**To Reproduce**
1. I Go to file src/contributors.json
2. Add comma after data name "Aadhavan"

**Expected behavior**
There a comma between data in contributors.json

**Screenshots**
![image](https://github.com/user-attachments/assets/35839ff5-be4b-4872-ae65-7780c8e924e2)
![image](https://github.com/user-attachments/assets/987e5996-2861-4656-b8e8-b80ad764187b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 129.0.6

**Additional context**
Sir @JollyJolli can you assign this issue to me Sir? I am new to open source contributions and I would love to contribute to your project Sir.

**Comment by wasif1** [comment]
assign this to me

**Comment by Phanty78** [comment]
Already solved. Thank you for your participation.
