### ISSUE TITLE
Code formatting and styling improvements.

### ISSUE THREAD

**Issue by TonyStark-19** [JollyJolli/HacktoberWall#148]
I will help you with formatting the code of your code files for better readability 
and will add some CSS related improvements to make the web page more visually appealing.
Assign me under hacktoberfest
Looking forward for your reply.

**Comment by Phanty78** [comment]
Okay, go ahead. @TonyStark-19 . You can check the existing issues too.

**Comment by JollyJolli** [comment]
Good idea!
