### ISSUE TITLE
The Halloween mode background doesn't exist

### ISSUE THREAD

**Issue by Phanty78** [JollyJolli/HacktoberWall#150]
Halloween was implemented but the associated background never seems to have been created. 

In general, this mode needs to be improved and makes the site less visually appealing at the moment.

New associated tasks will be added later here.

Tasks : 

- [ ] Add a background for Halloween mode in img folder.
- [ ] Name it : halloween-bg.webp
- [ ] The background img must be in webp format
- [ ] Test the application in different responsive mode and with different browser before pushing it

**Comment by JollyJolli** [comment]
Happy Contributing!
