### ISSUE TITLE
Edit "About Us" to be in a Card

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#162]
Add the "About us" section in a card, all the section should be inside of a card.

![image](https://github.com/user-attachments/assets/345b44b9-83bf-4681-b290-9eadf4bf32f9)

**Comment by ishan657** [comment]
Hy @JollyJolli 
I would like to work on this issue , Kindly assign this to me 
Thank you

**Comment by n-keerthi-gayathri** [comment]
@JollyJolli please assign me this issue

**Comment by shiv-0101** [comment]
did you mean that owner About us text and co-owner in one card...

So the entire section will look like just a border around...

If that's what needed, @JollyJolli assign it to me, I'll tweak it to look presentable as well..

**Comment by NagaJahnaviD** [comment]
hello @JollyJolli 
Could you assign me this issue?

**Comment by JollyJolli** [comment]
Sorry everyone, I will assign this to @ishan657 because he was the first one
