### ISSUE TITLE
Navbar styling issue in dark mode

### ISSUE THREAD

**Issue by opbot-xd** [JollyJolli/HacktoberWall#180]
**Describe the bug**
The navbar in dark mode has a black background

![image](https://github.com/user-attachments/assets/a1e743dc-83eb-42a6-b932-20faa31435ef)

**Comment by opbot-xd** [comment]
can i solve it?

**Comment by JollyJolli** [comment]
Yeah, happy contributing!

**Comment by opbot-xd** [comment]
![image](https://github.com/user-attachments/assets/7a2880fe-d9a3-436d-a0eb-23c717beb9fd)
