### ISSUE TITLE
Fixing the navbar . 

### ISSUE THREAD

**Issue by pbln** [JollyJolli/HacktoberWall#217]
![image](https://github.com/user-attachments/assets/eb254b07-f200-4860-891d-ea5d1f088989)
The pink color above the yellow background is just not visible , and needs improvement . Also the navbar as a whole looks a bit dull because of color scheme . I want to work on it . Kindly assign me this under hacktoberfest.

**Comment by Furiousfox-01** [comment]
can you assign me to improve the color scheme for the Navbar. @pbln

**Comment by JollyJolli** [comment]
Happy contributing!

**Comment by pbln** [comment]
![image](https://github.com/user-attachments/assets/b34c8d8a-ce3a-4b2e-81dc-3be9fd871797)
@JollyJolli how about this?

**Comment by JollyJolli** [comment]
I like it!
