### ISSUE TITLE
Solve the favicon problem

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#30]
The favicon is not appearing as expected when loading the HTML page. Despite having the appropriate link tag in the `<head>`, the favicon is not rendered in the browser tab.

**Steps to Reproduce:**
1. Open the HTML file in a browser.
2. Check the browser tab for the favicon.

**Expected Behavior:**
The favicon should display correctly in the browser tab.

**Actual Behavior:**
The favicon is not shown in the browser tab.

**Additional Information:**
- Confirmed that the favicon file path is correct.
- Tested in multiple browsers (Chrome, Firefox) with the same result.

Please investigate why the favicon is not being rendered properly in the HTML page.

**Comment by danyd6784** [comment]
Hi Jolly,

Can you list the files that are needed for this? I'm assuming that you're trying to link a favicon into both index.html and form.html? Are you trying to use the logo.png as the favicon?

**Comment by JollyJolli** [comment]
Hey @danyd6784 sorry i havent reply i was busy, and sorry because it looks like #31 was publish, if you want you can take another issue, there are a lot. 
But sorry for this
