### ISSUE TITLE
(!IMPORTANT!) Error with loading screen

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#64]
I need someone to solve this quick! The loading screen is just there and it dosent disapper! 
![image](https://github.com/user-attachments/assets/1586efe0-a038-41a6-a5c7-39c0dbd999bb)

**Comment by VinayakGaikwad101** [comment]
Let me have a look into it

**Comment by dheerajsingh01** [comment]
@VinayakGaikwad101  are you correcting it .
Otherwise, i can solve it.

**Comment by JollyJolli** [comment]
Both can help! I need this to work

**Comment by dheerajsingh01** [comment]
hey @JollyJolli check my PR. 
It resolve the error.

**Comment by JollyJolli** [comment]
THanks bro!

**Comment by dheerajsingh01** [comment]
Mention not ! 👍 
I am here.
