### ISSUE TITLE
The design of the card is looking simple, I want to make it look cool and also the text of the search bar is not visible properly.

### ISSUE THREAD

**Issue by danishsheikh1122** [JollyJolli/HacktoberWall#72]
The Contributors card is looking simple I can update and make it more stylish
<img width="1145" alt="Screenshot 2024-10-09 at 7 37 29 PM" src="https://github.com/user-attachments/assets/30331e38-ca55-4a49-8bee-dc5510b684a6">

see the 'search contributors' text is in pink which is not visible properly, I Can make it darker pink  
<img width="482" alt="Screenshot 2024-10-09 at 7 38 23 PM" src="https://github.com/user-attachments/assets/6dca6aa0-23f8-47de-ba7b-79618461e222">

hoping this issue will be assigned to me  to fix this issues

**Comment by JollyJolli** [comment]
Hey! Thanks for viewing all this! You are welcome to contribute on this.
