### ISSUE TITLE
The cards are green even in dark mode? Is this intentional?

### ISSUE THREAD

**Issue by Phanty78** [JollyJolli/HacktoberWall#76]
I noticed that the cards were no longer pink in dark mode but now green as in light mode. 

Is this intentional or a mistake?
If it's intentional, you'll need to update the modal to match the style of the rest of the page.

![image](https://github.com/user-attachments/assets/0f217bed-e95e-4f52-aa29-258e6be82398)

**Comment by JollyJolli** [comment]
Hey! Thanks for spotting this issue, I hadn't noticed it before. If you'd like to contribute, feel free—any help is appreciated!

**Comment by Phanty78** [comment]
Okay, I'll make it quick.

**Comment by JollyJolli** [comment]
Thanks! :)

**Comment by Phanty78** [comment]
Done.

**Comment by JollyJolli** [comment]
Thanks
