### ISSUE TITLE
[Enhancement] : Adding Sort option and pagination

### ISSUE THREAD

**Issue by srinidhifd** [JollyJolli/HacktoberWall#93]
Currently, the search functionality is the only option available. To enhance the user experience, you can add a Sort option next to the search bar. This would allow users to organize participants either alphabetically from A-Z or Z-A, giving them more control over how they view the list.

Additionally, by implementing pagination at the bottom of the page, users would be able to navigate through large numbers of participants more easily. This is especially important as the list grows, helping to improve readability and ensuring that the interface remains clean and efficient.

These improvements would significantly enhance usability, making the interface more intuitive and user-friendly.

![image](https://github.com/user-attachments/assets/1daa94ed-2665-41ce-b129-59c8551a8568)

@JollyJolli I would like to work on this issue . Assign this issue under "Hacktoberfest" Label .
Thank you

**Comment by JollyJolli** [comment]
Hi there!

Thank you for your suggestion! I really appreciate your input and think it’s a great idea. Feel free to start working on it!

However, I would like to hold off on implementing pagination for now. While it is a good concept, I want to prioritize other features at this time.

In the meantime, please proceed with the following tasks:

- [ ] Sort Option (A-Z)
- [ ] Sort Option (Z-A)

Looking forward to seeing your progress! Happy Contributing!
